name = "PoincareInvariants"
uuid = "26663084-47d3-540f-bd97-40ca743aafa4"
authors = ["Michael Kraus <michael.kraus@ipp.mpg.de>"]
version = "0.4.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
FFTW = "1"
